name: pyds-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pytest
  - pip:
    - codecov
    - pytest-cov
    - spin
    - meson
    - sphinx==5.0
    - sphinx-readable-theme==1.3.0
    - myst_nb==0.17.2
    - lcov
